name: test danger JS
on: [pull_request]

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 10.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - name: install yarn
        run: npm install -g pnpm
      - name: pnpm install
        run: |
          pnpm install  --frozen-lockfile
      - name: Danger
        run: |
          yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: true
