name: check-diff
on:
  push:
    branches:
      - develop
      - feature/c
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: check-diff
        run: |
          has_diff="$(git diff origin/main..HEAD -- readme.md | grep -c version)"
          echo "has_diff=$has_diff" >> "$GITHUB_OUTPUT"
      - id: echo
        if: ${{ steps.check-diff.outputs.has_diff == 2 }}
        run: echo "呼ばれたよ"
