name: test gihtub commands
on:
  workflow_dispatch:
    inputs:
      test:
        description: test
        required: true

jobs:
  check-github-commands:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: checkout new branch
        run: |
          git checkout -b new_branch
      - name: check if branch exists
        id: check_branch
        run: |
          git branch -r
          echo "git branch -r | grep new_branch"
          echo "git branch -r | grep new_branch | wc -l"
          echo "is_branch_exists=(git branch -r | grep new_branch | wc -l)" >> $GITHUB_OUTPUT
      - name: pull current state
        if: ${{steps.check_branch.outputs.is_branch_exists != 0}}
        run: |
          git config pull.rebase false
          git pull origin new_branch
      - name: change some file
        run: |
          echo 'some change' >> readme.md
      - name: commit new change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: add some change
          branch: new_branch
