name: test gihtub commands
on:
  workflow_dispatch:
    inputs:
      test:
        description: test
        required: true

jobs:
  check-github-commands:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
        with:
          ref: sample_branch
      - name: show branch
        run: |
          git branch
