name: test gihtub commands
on:
  workflow_dispatch:
    inputs:
      test:
        description: test
        required: true

jobs:
  check-github-commands:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: check if branch exists
        id: check_branch
        run: |
          git fetch origin
          git branch
          echo "$(git branch | grep -c new_branch)"
          echo "is_branch_exists=$(git branch | grep -c new_branch)" >> $GITHUB_OUTPUT
      - name: checkout new branch
        if: ${{steps.check_branch.outputs.is_branch_exists != 0}}
        run: |
          git checkout new_branch
      - name: checkout new branch 2
        if: ${{steps.check_branch.outputs.is_branch_exists != 0}}
        run: |
          git checkout -b new_branch
      - name: pull current state
        if: ${{steps.check_branch.outputs.is_branch_exists != 0}}
        run: |
          git config pull.rebase false
          git pull origin new_branch
      - name: change some file
        run: |
          echo 'some change' >> readme.md
      - name: commit new change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: add some change
          branch: new_branch
