name: test gihtub commands to create-pr
on:
  workflow_dispatch:
    inputs:
      test:
        description: test
        required: true

jobs:
  check-github-commands:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: test
          branch: test
          commit_options: "--allow-empty"
